"""create admin_role table

Revision ID: 379fd34a16b6
Revises: 93891ab481be
Create Date: 2025-10-05 16:55:28.586822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379fd34a16b6'
down_revision: Union[str, Sequence[str], None] = '93891ab481be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('A', 'I', name='statusenum'), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=True),
    sa.Column('site_setting', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('banner', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('category', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('currency', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('tax_data', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('country', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('state', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('city', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('media_gallery', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('all_user', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('chat', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('rating', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('site_content', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('email_template', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('sms_template', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('rest_api', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('payment_plan', sa.Enum('Y', 'N', name='yesnoenum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_role_id'), 'admin_role', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_role_id'), table_name='admin_role')
    op.drop_table('admin_role')
    # ### end Alembic commands ###
