"""create social_newtworking_links

Revision ID: 511647c0e5a4
Revises: f8536a1b057a
Create Date: 2025-10-25 10:26:29.259384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511647c0e5a4'
down_revision: Union[str, Sequence[str], None] = 'f8536a1b057a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_networking_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('I', 'A', name='socialmediastatusenum'), nullable=False),
    sa.Column('social_name', sa.String(length=50), nullable=True),
    sa.Column('social_link', sa.String(length=200), nullable=True),
    sa.Column('social_logo', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_networking_links_id'), 'social_networking_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_networking_links_id'), table_name='social_networking_links')
    op.drop_table('social_networking_links')
    # ### end Alembic commands ###
