"""create side_config table

Revision ID: fbcf239999ec
Revises: 4b43e9a93a3a
Create Date: 2025-10-13 14:43:21.094541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbcf239999ec'
down_revision: Union[str, Sequence[str], None] = '4b43e9a93a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('I', 'A', name='configstatusenum'), nullable=False),
    sa.Column('web_name', sa.String(length=200), nullable=True),
    sa.Column('web_frienly_name', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.String(length=100), nullable=True),
    sa.Column('favicon', sa.String(length=100), nullable=True),
    sa.Column('contact_no', sa.String(length=50), nullable=True),
    sa.Column('website_title', sa.String(length=100), nullable=True),
    sa.Column('website_description', sa.String(length=500), nullable=True),
    sa.Column('website_keywords', sa.String(length=500), nullable=True),
    sa.Column('google_analytics_code', sa.String(length=500), nullable=True),
    sa.Column('footer_text', sa.String(length=500), nullable=True),
    sa.Column('about_footer', sa.String(length=500), nullable=True),
    sa.Column('from_email', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=50), nullable=True),
    sa.Column('full_address', sa.String(length=500), nullable=True),
    sa.Column('map_address', sa.Text(), nullable=True),
    sa.Column('sms_api', sa.String(length=500), nullable=True),
    sa.Column('sms_api_status', sa.Enum('I', 'A', name='configstatusenum'), nullable=False),
    sa.Column('android_app_link', sa.String(length=100), nullable=True),
    sa.Column('ios_app_link', sa.String(length=100), nullable=True),
    sa.Column('current_date_crone', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('smtp_host', sa.Text(), nullable=True),
    sa.Column('smtp_port', sa.String(length=50), nullable=True),
    sa.Column('smtp_user', sa.Text(), nullable=True),
    sa.Column('smtp_pass', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_config_id'), 'site_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_config_id'), table_name='site_config')
    op.drop_table('site_config')
    # ### end Alembic commands ###
